### ISSUE TITLE
zoom/warp calculation

### ISSUE THREAD

**Issue by gzalles** [thomasdeppisch/hoast360#13]
could you possibly provide some information about the calculation of the zoom/warping matrices? 

having a tough time understanding this transform. I found a few papers but they are a bit confusing. I am guessing you used Matlab or some other numerical analysis tool. 

a gist would be appreciated. 

thanks

**Comment by thomasdeppisch** [comment]
Hi,

Have a look at our AES e-brief, there we describe the zoom (it's openly accessible): https://www.aes.org/e-lib/browse.cfm?elib=20828

You are right, we pre-computed the zoom steps in Matlab. Unfortunately the code is not really clean and has some dependencies so it's not really suitable for sharing...

**Comment by gzalles** [comment]
I did read the brief. Perhaps I could re-phrase my question:

* where can I find more information about those two transforms: windowing and warping?

I know Github issues are not really about this. I appreciate your help. It feels to me like the next brief could add more detail about these two transforms. 😄

Thanks,
Gabe

**Comment by gzalles** [comment]
thanks. I will take a look. closing this issue
