### ISSUE TITLE
cannot pass URI to IRs

### ISSUE THREAD

**Issue by umlaeute** [thomasdeppisch/hoast360#3]
i'm attempting to use HOAST360 with remote media.

my HTML looks like:

~~~js
<script src="https://example.com/hoast/hoast360/dist/hoast360.bundle.js"></script>
<script>
    var hoast360 = new HOAST360();
    var ambisonicsOrder = 4;
    hoast360.initialize("https://example.com/hoast/hoast360/media/hoast_demo_o4/", "https://example.com/hoast/hoast360/irs/", ambisonicsOrder);
</script>
~~~

but this gives me an ugly error:

> Browser cannot decode audio data:  https://example.com/https://example.com/hoast/hoast360/irs/hoast_o4_05-12ch.wav
> 
> Error: EncodingError: MediaDecodeAudioDataUnknownContentType
> 
> (If you re using Safari and get a null error, this is most likely due to Apple's shady plan going on to stop the .ogg format from easing web developer's life :)
> 

the problem is obviously that `protocol://hostname` is prepended to my `newIrUrl` parameter.

if I use the following, everything works as expected:
```js
    hoast360.initialize("https://example.com/hoast/hoast360/media/hoast_demo_o4/", "/hoast/hoast360/irs/", ambisonicsOrder);
```

however, `"/hoast/hoast360/irs/"` is not a *URL* (as `newIrUrl` suggests)

**Comment by thomasdeppisch** [comment]
You are right, `newIrUrl` should rather be called something like `newIrPath` as it holds a relative path to the IRs.
We did not consider remote media so far, how is this working for you? I imagine you would like to have remote media but use local IRs? Prepending `protocol://hostname` helps us to develop locally without thinking about deployment but in your case it is probably not the best solution. Do you see a better solution here?

**Comment by umlaeute** [comment]
how about just checking whether the `newIrUrl` starts with `http://` (resp. `https://`), and if so, don't prepend `protocol://hostname`?
