### ISSUE TITLE
use a single manifest file for audio and video.

### ISSUE THREAD

**Issue by umlaeute** [thomasdeppisch/hoast360#5]
it's really annoying that we have to specify both a `video.mpd` and an `audio.mpd`.
instead i really would like to point the player to my `example.mpd` that contains two adaption-sets: one for audio, one for video.

i *guess* the reason is, that the current approach makes it a bit easier to keep video.js from interfering with the sound (as it doesn't have any sound to play), but from a user perspective, it makes things unwieldy.

**Comment by thomasdeppisch** [comment]
You're absolutely right, I already started working on a branch to support single mpds:
https://github.com/thomasdeppisch/hoast360/tree/single_mpd

It already works with mpds I created for testing, unfortunately there seems to be a problem with live streams at the moment.

**Comment by thomasdeppisch** [comment]
Now the build on the single_mpd branch is also working in live mode (e.g. with a stream from OBS ME and Earshot). I will do some more testing and then merge it into master. Let me know how it is working for you.

**Comment by umlaeute** [comment]
it seems to be working somehow!
(I still need to do some tweaking when transcoding to multiple resolutions, but afaik this is a problem entirely on my side)
